import {HOSTED_DEMO,HOSTED_NOTICE} from './hosting.js';
import React,{useEffect,useRef,useState} from 'react';
import {Compass,Cpu,Image as ImageIcon,ShieldCheck,Download,Square,Trash2} from 'lucide-react';
import {CULTURES,culturalGuidance} from './engine.js';
import {cultureRequest,acceptsPhoto,checkDraft} from './model/culture-policy.js';
import {inspectDevice,currentCultureMode,prepareCultureModel,stopCultureModel,generateCulture,describePhoto,cachedCultureMode,removeCulturePack,cultureManifest} from './model/culture-service.js';

export default function CultureAssistant(){
 const [mode,setMode]=useState(HOSTED_DEMO?'basic':'text'),[device,setDevice]=useState(null),[ready,setReady]=useState(currentCultureMode),[cached,setCached]=useState({}),[busy,setBusy]=useState(false),[status,setStatus]=useState(''),[text,setText]=useState(''),[result,setResult]=useState(null),[photo,setPhoto]=useState(null),[preview,setPreview]=useState(null);
 const task=useRef(0),photoInput=useRef(null),previewRef=useRef(null);
 useEffect(()=>{inspectDevice().then(setDevice).catch(()=>{});Promise.all(['text','vision'].map(async m=>[m,await cachedCultureMode(m)])).then(entries=>setCached(Object.fromEntries(entries))).catch(()=>{});return()=>{task.current++;stopCultureModel();if(previewRef.current)URL.revokeObjectURL(previewRef.current)}},[]);
 function stop(){task.current++;stopCultureModel();setReady(null);setBusy(false);setStatus('Stopped. You can still use bundled guidance.')}
 function choose(value){stop();setMode(value);setResult(null);setStatus('');setPhoto(null);setPreview(null);if(previewRef.current)URL.revokeObjectURL(previewRef.current);previewRef.current=null}
 async function prepare(){const id=++task.current;setBusy(true);setResult(null);setReady(null);try{await prepareCultureModel(mode,s=>{if(id===task.current)setStatus(s)});if(id===task.current){setDevice(await inspectDevice());setReady(mode);setCached(c=>({...c,[mode]:true}));setStatus('Ready. This pack runs locally; no cloud fallback.')}}catch(e){if(id===task.current){setStatus(e.message);if(!currentCultureMode())setReady(null)}}finally{if(id===task.current)setBusy(false)}}
 async function ask(e){e?.preventDefault();setResult(null);if(mode==='basic'){if(text.trim())setResult({bundled:culturalGuidance(text),question:text});return}
  const id=++task.current;setBusy(true);setStatus('Working on this device…');
  try{
   if(mode==='vision'){
    if(!photo)throw new Error('Choose a photo of an object or setting first.');
    const generated=await describePhoto(photo);if(id===task.current)setResult({...generated,photo:true});
   }else{
    const request=cultureRequest(text);
    if(request.fallback){setResult({fallback:request.fallback});setStatus('Using a clarification fallback.');return}
    const generated=await generateCulture(request.messages);if(id===task.current)setResult({...generated,...checkDraft(generated.text,request.cards[0]),cards:request.cards});
   }
   if(id===task.current)setStatus('Finished locally. Review the draft before using it.');
  }catch(e){if(id===task.current){setStatus(e.message);if(!currentCultureMode())setReady(null)}}finally{if(id===task.current)setBusy(false)}
 }
 async function selectPhoto(e){
  const file=e.target.files?.[0];setResult(null);setPhoto(null);setStatus('');if(!file)return;
  if(!acceptsPhoto(file)){setStatus('Choose a JPEG, PNG or WebP image under 8 MB.');e.target.value='';return}
  const id=++task.current;
  try{
   const bitmap=await createImageBitmap(file);if(bitmap.width*bitmap.height>24e6){bitmap.close();throw new Error('Choose a smaller photo (under 24 megapixels).')}
   const scale=Math.min(1,512/Math.max(bitmap.width,bitmap.height)),canvas=document.createElement('canvas');canvas.width=Math.round(bitmap.width*scale);canvas.height=Math.round(bitmap.height*scale);const ctx=canvas.getContext('2d');ctx.fillStyle='#fff';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close();
   const rgba=ctx.getImageData(0,0,canvas.width,canvas.height).data,pixels=new Uint8ClampedArray(canvas.width*canvas.height*3);for(let i=0,j=0;i<rgba.length;i+=4){pixels[j++]=rgba[i];pixels[j++]=rgba[i+1];pixels[j++]=rgba[i+2]}
   const blob=await new Promise(resolve=>canvas.toBlob(resolve,'image/jpeg',.85));if(id!==task.current)return;
   if(previewRef.current)URL.revokeObjectURL(previewRef.current);previewRef.current=URL.createObjectURL(blob);setPreview(previewRef.current);setPhoto({pixels,width:canvas.width,height:canvas.height});setStatus('Photo resized locally. File metadata is not sent to the model.');
  }catch(e){if(id===task.current)setStatus(e.message)}
 }
 const pack=mode==='basic'?null:cultureManifest[mode==='text'?(device?.textPack||'lite'):mode];
 return <><div className="page-heading"><div><div className="eyebrow">CULTURE · CURIOSITY · YOUR CHOICE</div><h1>A little context. A kinder question<span>.</span></h1><p>Explore possible meanings, then check with the person in front of you.</p></div></div>
 <section className="device-options" aria-label="Choose assistance for your device">
  {[['basic',Compass,'Everyday','Bundled guidance','For basic phones and limited data. No LLM download.'],['text',Cpu,'Text assistant','Optional local LLM','Adapt a respectful reply to your situation.'],['vision',ImageIcon,'Photo assistant','8 GB+ and WebGPU required','Describe visible objects or a setting.']].map(([id,Icon,title,subtitle,description])=><button key={id} className={'device-option '+(mode===id?'selected':'')} aria-pressed={mode===id} disabled={HOSTED_DEMO&&id!=='basic'||id==='vision'&&!device?.canVision} onClick={()=>choose(id)}><Icon size={23}/><strong>{title}</strong><span>{subtitle}</span><p>{description}</p></button>)}
 </section>
 <div className="device-note"><ShieldCheck size={17}/><p>{HOSTED_DEMO?'Hosted demo: Everyday guidance is available. Text and photo models require the full localhost version.':device?`${device.memoryGB?`Browser reports approximately ${device.memoryGB} GB RAM`:'Memory information unavailable'}. ${device.saveData?'Data Saver is on. ':''}${device.recommended==='basic'?'Everyday mode is the suggested starting point.':'Text assistant is worth testing on this device.'}`:'Checking this device…'} {!HOSTED_DEMO&&(device?.backend==='webgpu'?'WebGPU is available: accelerated text and photo modes enabled.':'Small text model selected on CPU/WASM. Photos are unavailable. WebGPU requires at least 8 GB reported RAM and a compatible browser.')} Memory reports are approximate; unknown memory uses the small text model. Nothing downloads automatically.</p></div>
 <div className="culture-layout"><section>
 {pack&&<section className="white-card culture-pack"><div className="eyebrow">OPTIONAL · RUNS ON YOUR DEVICE</div><h2>{mode==='text'?'Words for an awkward moment':'A little help seeing the scene'}</h2><p>{mode==='text'?'The LLM rewrites suggested wording from the matching Safar note into simple English. Your written situation selects the note; the LLM only sees the suggested wording. It is not an authority on Pakistani culture.':'Choose an object or a setting you have permission to use. A picture cannot establish someone’s culture, consent, intentions or safety.'}</p><div className="tags"><span>{pack.name}</span><span>{Math.ceil(pack.bytes/1e6)} MB pack {device?.backend==='webgpu'&&mode==='text'?'· runtime included':'+ shared 22 MB runtime'}</span><span>{device?.backend==='webgpu'?'WebGPU':'CPU / WASM'} · English · Experimental</span></div><p className="subtle">Prepare over Wi-Fi or a local hotspot. Files come from this local app. Allow free space for browser copies; preparation and inference may be slow. Only one culture model runs at a time. On eligible devices, the text pack is shared with Talk’s translation; no second download is needed.</p><button className="primary-button" disabled={busy||ready===mode||!device||(mode==='vision'&&!device.canVision)} onClick={prepare}><Download size={17}/>{ready===mode?'Ready on this device':cached[mode]?'Start cached pack':'Prepare '+(mode==='text'?'text':'photo')+' pack'}</button>{cached[mode]&&!busy&&<button className="back-link model-remove" onClick={async()=>{try{await removeCulturePack(mode);setReady(null);setCached(c=>({...c,[mode]:false}));setStatus('This model pack was removed. Shared runtime and conversations remain.')}catch(e){setStatus(e.message)}}}><Trash2 size={15}/> Remove this pack</button>}</section>}
 <form className="white-card culture-form" onSubmit={ask}>
 {mode==='vision'?<><label htmlFor="culture-photo">Photo of an object or setting</label><input ref={photoInput} id="culture-photo" type="file" accept="image/jpeg,image/png,image/webp" disabled={busy} onChange={selectPhoto}/>{preview&&<img className="culture-photo" src={preview} alt="Selected photo, resized locally"/>}<p className="subtle">Avoid faces, private documents and personal details. The image stays in memory and is discarded when you leave this screen. Small text and Urdu signs may be read incorrectly.</p></>:<><label htmlFor="culture-question">{mode==='text'?'Describe the situation · English':'Describe what happened'}</label><textarea id="culture-question" rows={4} maxLength={600} disabled={busy} placeholder="The host kept offering more food after I said I was full…" value={text} onChange={e=>setText(e.target.value)}/></>}
 <div className="culture-actions"><button className="primary-button" disabled={busy||(mode==='vision'?!photo:!text.trim())||(mode!=='basic'&&ready!==mode)}><Compass size={18}/>{mode==='vision'?'Describe this photo':mode==='text'?'Rephrase suggested wording':'Help me understand'}</button>{busy&&<button type="button" className="secondary-button" onClick={stop}><Square size={15}/> Stop</button>}</div><p role="status" className="notice">{status||'Your input and results are not saved or sent to a server.'}</p></form>
 {result&&<article className="white-card culture-result" aria-live="polite"><div className="eyebrow">{result.bundled?'BUNDLED GUIDANCE':result.fallback?'ASK FOR CLARIFICATION':result.photo?'UNREVIEWED PHOTO DESCRIPTION':result.usedFallback?'BUNDLED FALLBACK · DRAFT DID NOT PASS CHECKS':'LLM DRAFT · CHECK BEFORE USING'}</div>{result.bundled?<><h2>A possible perspective</h2><p>{result.bundled.explanation}</p><p>{result.bundled.not}</p><blockquote>{result.bundled.action}</blockquote></>:result.fallback?<p>{result.fallback}</p>:<>{result.cards&&<div className="grounded-context"><strong>Bundled context · a possibility</strong><p>{result.cards[0].explanation}</p><p>{result.cards[0].not}</p><strong>Bundled wording to compare</strong><p>{result.cards[0].action}</p></div>}<p className="generated-culture">{result.text||'No useful draft was generated. Ask the person directly.'}</p><p className="subtle">{(result.elapsedMs/1000).toFixed(1)} seconds · {result.backend==='webgpu'?'WebGPU':'CPU / WASM'} · Processed locally</p><div className="human-note"><ShieldCheck size={17}/>{result.photo?'This description may miss or invent details. Confirm what is visible; do not use it to infer cultural meaning.':'Check that this wording preserves your meaning and respects the other person’s choice. You choose what to say.'}</div>{result.cards&&<details className="culture-sources"><summary>Source notes used to choose wording</summary>{result.cards.map(c=><div key={c.id}><strong>{c.title}</strong><p>{c.explanation} {c.not}</p></div>)}<p>Illustrative Safar prototype notes. Local community review is still needed. Matching a note does not guarantee a faithful rewrite.</p></details>}</>}</article>}
 </section><aside><div className="white-card"><h2>Start with a familiar moment</h2><div className="culture-examples">{CULTURES.map(c=><button key={c.id} disabled={busy||mode==='vision'} onClick={()=>{setText(c.question);setResult(mode==='basic'?{bundled:c}:null)}}><Compass size={17}/>{c.title}</button>)}</div></div><div className="aside-note"><h3>Help with words. Room for differences.</h3><p>Family, region, language and personal preferences all matter. Ask instead of assuming. A polite refusal is always an option.</p><p>These models have not been evaluated for Urdu, Roman Urdu or Pakistan’s regional languages. English generation is experimental. Existing Urdu phrases remain available in Talk.</p></div></aside></div></>
}
