import React from 'react';
import {ArrowUpRight,Sprout,ShieldCheck,WifiOff,Users} from 'lucide-react';
import {recordsForInsights} from './records.js';
export default function Pilot({conversations}){
 const saved=recordsForInsights(conversations).length;
 return <div className="pilot-page"><div className="page-heading"><div><div className="eyebrow">SMALL AI · LOCAL LIVELIHOODS</div><h1>One useful conversation.<br/>One affordable next step.</h1><p>Safar helps small tourism operators understand a request, test a paid experience and decide what to repeat.</p></div></div>
 <section className="trial-home-link"><div><span className="eyebrow"><Sprout size={16}/> THE BUSINESS CASE</span><h2>Turn informal interest into a carefully sized trial.</h2><p>Noor already has skills, stories and a working farm. Safar helps her see what visitors ask for and set a price, capacity and workload she can review herself.</p></div><a href="#trial" className="primary-button">Walk through Noor’s story <ArrowUpRight size={17}/></a></section>
 <div className="pilot-grid"><section className="white-card"><Users className="pilot-icon"/><h2>Who benefits, who pays?</h2><p><strong>Operator:</strong> keeps the visitor relationship and makes the business decisions. No booking commission or payment processing is built into this prototype.</p><p><strong>Proposed buyer:</strong> a tourism association, cooperative or local development program funds onboarding, language review and maintenance for a group of operators.</p><p><strong>First pilot:</strong> co-design with 5–10 operators and a local language reviewer over four weeks. Test one activity per operator before expanding.</p><small>Business-model hypothesis. No customer, partner, contract or field income has been established.</small></section>
 <section className="white-card"><WifiOff className="pilot-icon"/><h2>Fit the phone people have.</h2><p>Authored phrases, visitor records, business planning and saved meeting instructions work offline after the app is prepared.</p><p>Small downloads add intent understanding and compact translation. Compatible devices reporting 8 GB+ RAM can use one shared quantized WebGPU model for translation and Culture.</p><p>Prepare large packs over a shared hotspot. There is no per-message cloud inference bill; device, training and maintenance costs still matter.</p><small>Feature phones cannot run this web app. The shared smartphone journey is a design assumption that needs field testing. Map tiles and device speech may need internet.</small></section></div>
 <section className="white-card pilot-measures"><h2>Measure whether it helps Noor.</h2><div className="pilot-measure"><strong>Understanding</strong><p>A fluent reviewer checks new English–Urdu messages, especially prices, quantities, directions and permission. Log errors and corrections.</p></div><div className="pilot-measure"><strong>Access</strong><p>Record actual phone and browser models, download size, completion time, failures and offline task completion.</p></div><div className="pilot-measure"><strong>Livelihoods</strong><p>Track reviewed requests, direct confirmations, attendance, all trial costs including time, amount left and Noor’s repeat/change/stop decision.</p></div><div className="pilot-measure"><strong>Agency</strong><p>Ask whether the visitor agreed to saving their words and whether Noor could understand, correct or reject every suggestion.</p></div><p className="trial-fine">A topic mention is not willingness to pay. A saved conversation is not a unique person. A single positive trial is not evidence of sustained income.</p></section>
 <section className="white-card"><div className="eyebrow"><ShieldCheck size={16}/> EVIDENCE YOU CAN INSPECT</div><h2>Your records, with their source clear.</h2><div className="model-facts"><span><strong>{saved}</strong>saved conversations</span></div><p>All saved conversations inform insights, including any sample records. Counts are not verified unique visitors or bookings. Originals, translation model details and intent suggestions remain visible in Visitors. Review the source before acting.</p><div className="pilot-links"><a href="#visitors">Review visitor records <ArrowUpRight size={16}/></a><a href="#model">Inspect AI test evidence <ArrowUpRight size={16}/></a><a href="#map">Check the meeting point <ArrowUpRight size={16}/></a></div></section>
 <p className="trial-fine">Hackathon prototype. Noor is a fictional challenge persona. Urdu and PKR are illustrative localization choices; the coffee-farm scenario is not a field study of rural Pakistan. Local community review and physical phone trials remain necessary.</p></div>;
}
