import {HOSTED_DEMO,HOSTED_NOTICE} from './hosting.js';
import React,{useEffect,useState} from 'react';
import './talk-ai.css';
import {Cpu,Download,Check} from 'lucide-react';
import {hasCachedModel,isModelReady,loadSemanticModel} from './model/service.js';
export default function TalkModelControl({onReady}){
 const [ready,setReady]=useState(isModelReady),[cached,setCached]=useState(false),[busy,setBusy]=useState(false),[status,setStatus]=useState('Checking downloaded files…');
 useEffect(()=>{let live=true;async function init(){if(HOSTED_DEMO){setStatus('AI downloads are disabled here. Use the localhost instructions above.');onReady(false);return}try{if(isModelReady()){setStatus('Ready for English visitor messages.');onReady(true);return}const saved=await hasCachedModel();if(!live)return;setCached(saved);if(!saved){setStatus('Optional download · about 46 MB including the browser runtime.');return}setBusy(true);setStatus('Starting your downloaded classifier…');await loadSemanticModel(s=>{if(live)setStatus(s)});if(live){setReady(true);onReady(true);setStatus('Downloaded classifier restarted. New English messages use it automatically.')}}catch(e){if(live){setStatus(e.message);onReady(false)}}finally{if(live)setBusy(false)}}init();return()=>{live=false}},[]);
 async function start(){setBusy(true);try{await loadSemanticModel(setStatus);setReady(true);setCached(true);onReady(true);setStatus('Ready. Send an English visitor message to see its intent below.')}catch(e){setStatus(e.message);onReady(false)}finally{setBusy(false)}}
 return <section className="talk-ai-control" aria-label="Trained intent classifier"><div className="talk-ai-heading"><Cpu size={23}/><div><strong>Safar’s trained intent classifier</strong><span>{ready?'Active on this device':busy?'Starting on this device':'Not running · phrase and rule fallback'}</span></div>{ready&&<Check size={20}/>}</div><p>MiniLM + Safar’s trained classifier · 12 request types · English</p><div className="talk-ai-actions">{!ready&&<button className="primary-button" onClick={start} disabled={busy||HOSTED_DEMO}><Download size={16}/>{busy?'Starting classifier…':cached?'Start downloaded classifier':'Prepare intent classifier'}</button>}<a href="#model">View training & test results</a></div><p className="talk-ai-status" role="status">{status}</p><small>Intent tells you what the visitor is asking. Translation uses separate language packs and instant phrases. Messages stay on this device.</small></section>
}
