import {HOSTED_DEMO,HOSTED_NOTICE} from './hosting.js';
import React,{useEffect,useState} from 'react';
import {Languages,Download,Square,Cpu} from 'lucide-react';
import {hasTranslationPack,prepareTranslationPack,removeTranslationPack,stopTranslation,watchTranslation,translationManifest,translationEngine,setTranslationEngine} from './model/translation-service.js';
import {inspectLLMDevice,hasSharedLLM,prepareSharedLLM,removeSharedLLM,watchSharedLLM,sharedLLMManifest} from './model/shared-llm-service.js';
export default function TranslationControl({language}){
 const [src,setSrc]=useState(language),[cached,setCached]=useState({}),[gpuSaved,setGpuSaved]=useState(false),[device,setDevice]=useState(null),[engine,setEngine]=useState(translationEngine),[busy,setBusy]=useState(false),[status,setStatus]=useState('');
 useEffect(()=>setSrc(language),[language]);
 useEffect(()=>{let live=true;Promise.all(['en','ur'].map(async s=>[s,await hasTranslationPack(s)])).then(x=>{if(live)setCached(Object.fromEntries(x))}).catch(()=>{});inspectLLMDevice().then(x=>{if(live)setDevice(x)}).catch(()=>{});hasSharedLLM().then(x=>{if(live)setGpuSaved(x)}).catch(()=>{});const off=watchTranslation(setStatus),offGPU=watchSharedLLM(setStatus);return()=>{live=false;off();offGPU()}},[]);
 async function prepare(gpu=false){setBusy(true);try{if(gpu){await prepareSharedLLM();setGpuSaved(true)}else{await prepareTranslationPack(src);setCached(c=>({...c,[src]:true}))}}catch(e){setStatus(e.message)}finally{setBusy(false)}}
 if(HOSTED_DEMO)return <section className="translation-control" aria-label="On-device translation"><strong>AI translation · localhost only</strong><p>General translation models are not included in this hosted demo. Use the localhost instructions above.</p><p>Use “Choose a translated phrase” for the bundled English–Urdu phrases.</p></section>;
 return <section className="translation-control" aria-label="On-device translation"><div className="talk-ai-heading"><Languages size={22}/><div><strong>Translate English ↔ Urdu</strong><span>Private drafts · saved packs work offline</span></div></div>
 {device?.eligible&&<div className="gpu-pack"><strong><Cpu size={16}/> Shared 4-bit language assistant</strong><p>{sharedLLMManifest.label} · WebGPU · used by translation and Culture. Prepare once over Wi-Fi or a local hotspot.</p><div className="translation-controls"><select aria-label="Translation engine" value={engine} disabled={busy} onChange={e=>{setEngine(e.target.value);setTranslationEngine(e.target.value)}}><option value="auto">Use WebGPU when pack is ready</option><option value="compact">Use compact CPU translation</option></select>{gpuSaved?<span className="translation-ready">Shared pack saved</span>:<button className="primary-button" disabled={busy} onClick={()=>prepare(true)}><Download size={15}/>{busy?'Preparing…':`Prepare ${(sharedLLMManifest.bytes/1e9).toFixed(2)} GB shared pack`}</button>}</div></div>}
 <div className="translation-controls"><select aria-label="Translation pack" value={src} onChange={e=>setSrc(e.target.value)} disabled={busy}><option value="en">English → Urdu</option><option value="ur">Urdu → English</option></select>{cached[src]?<span className="translation-ready">Compact CPU pack saved</span>:<button className="secondary-button" disabled={busy} onClick={()=>prepare(false)}><Download size={15}/>{busy?'Preparing…':`Prepare ${Math.ceil(translationManifest[src].bytes/1e6)} MB compact pack`}</button>}</div>
 <p>{device?.eligible&&gpuSaved&&engine==='auto'?'New unfamiliar messages use the shared WebGPU model.':'Unfamiliar wording uses the compact model when its pack is saved.'} Supported phrases are instant. Every generated translation is a draft: confirm meaning with the speaker.</p>
 {device&&!device.eligible&&<p>{device.reason} Compact translation uses the CPU.</p>}
 <details><summary>Translation controls & limitations</summary><p>Models can change meaning. Check names, prices, quantities and refusals. Urdu script is supported; Roman Urdu has not been evaluated. Original words and the model used stay in the visitor record. No automatic booking, payment or message sharing occurs.</p><p>The shared LLM uses 4-bit weights with half-precision operations. WebGPU requires 8 GB+ reported RAM and a compatible GPU; browser memory reports are approximate. The WebLLM runtime is included in its pack. Compact packs add up to 22 MB shared runtime if missing. Idle model memory is released after a minute.</p><div className="translation-controls"><button className="secondary-button" onClick={()=>stopTranslation()}><Square size={14}/> Stop translation</button>{cached[src]&&<button className="secondary-button" disabled={busy} onClick={async()=>{try{await removeTranslationPack(src);setCached(c=>({...c,[src]:false}))}catch(e){setStatus(e.message)}}}>Remove compact pack</button>}{gpuSaved&&<button className="secondary-button" disabled={busy} onClick={async()=>{try{await removeSharedLLM();setGpuSaved(false)}catch(e){setStatus(e.message)}}}>Remove shared WebGPU pack</button>}</div></details><p role="status">{status}</p></section>
}
