import {HOSTED_DEMO,HOSTED_NOTICE} from './hosting.js';
import React,{useEffect,useMemo,useState} from 'react';
import {ArrowRight,Check,MapPin,Sprout,ShieldCheck,Copy,Cpu} from 'lucide-react';
import {TRIAL_KEY,DEMO_NOTES,DEMO_PLAN,currentNotes,selectedParties,validatePlan,economics,validateOutcome,offerText,newTrial,loadTrial} from './trial.js';
import {loadSemanticModel,predictSemantic} from './model/service.js';
import './trial.css';
const money=n=>new Intl.NumberFormat('en-PK',{maximumFractionDigits:0}).format(n);
const steps=['Listen','Plan a trial','Review offer','Learn & decide'];
function Field({label,value,onChange,type='text',...rest}){return <label className="trial-field"><span>{label}</span><input type={type} value={value} onChange={e=>onChange(e.target.value)} {...rest}/></label>}
export default function TrialJourney({conversations}){
 const [trial,setTrial]=useState(loadTrial),[errors,setErrors]=useState([]),[saveError,setSaveError]=useState(''),[status,setStatus]=useState(''),[ai,setAi]=useState(null),[busy,setBusy]=useState(false);
 const demo=trial.source==='demo';
 const notes=useMemo(()=>demo?DEMO_NOTES:currentNotes(conversations),[demo,conversations]);
 const selected=trial.selected.filter(id=>notes.some(n=>n.id===id));
 const parties=selectedParties(notes,selected),plan=trial.plan,calc=economics(plan),valid=validatePlan(plan).length===0;
 useEffect(()=>{try{localStorage.setItem(TRIAL_KEY,JSON.stringify(trial));setSaveError('')}catch{setSaveError('Changes could not be saved. Keep this window open.')}},[trial]);
 function update(change){setTrial(t=>({...t,...change}));setErrors([]);setStatus('')}
 function changePlan(k,v){update({plan:{...plan,[k]:v},approved:false,finished:false})}
 function go(step){if(step===1&&!selected.length){setErrors(['Select at least one source message you have reviewed.']);return}if(step===2){const e=validatePlan(plan);if(e.length){setErrors(e);return}}update({step});window.scrollTo(0,0)}
 async function analyze(){setBusy(true);setAi(null);try{await loadSemanticModel(setStatus);const r=await predictSemantic(DEMO_NOTES[5].text);setAi(r);setStatus('Analysis complete on this device. Review the visitor’s words yourself.')}catch(e){setStatus(e.message)}finally{setBusy(false)}}
 async function copy(){try{await navigator.clipboard.writeText(offerText(plan,demo));setStatus('Offer copied. You choose whether and how to share it.')}catch{setStatus('Copy unavailable. Select the offer text below and copy it manually.')}}
 function finish(){const e=validateOutcome(trial.outcome,plan);if(e.length){setErrors(e);return}update({finished:true});setStatus('Review saved on this device.');window.scrollTo(0,0)}
 return <div className="trial-page"><div className="page-heading"><div><div className="eyebrow"><Sprout size={16}/> FROM INTEREST TO A SMALL FIRST STEP</div><h1>Try small. Learn what works.</h1><p>Turn visitor requests into one experience you can afford to test.</p></div></div>
 <div className="trial-context"><span className="trial-badge">{demo?'FICTIONAL DEMONSTRATION':'YOUR LOCAL WORKSPACE'}</span><p>{demo?'Noor borrows a family phone at the weekend. Six visiting parties over a month leave a few requests. Can she test a 45-minute roasting and tasting session alongside her usual work?':'Review your own visitor messages, set the practical limits, and decide whether to run one trial.'}</p><small>{demo?'Adapted from the challenge’s fictional coffee-farm persona. PKR amounts and all outcomes are illustrative Pakistan localization assumptions, not field research.':'All saved visitor messages appear here. Check their source and meaning before selecting evidence.'}</small><details><summary>Choose a workspace</summary><p>Changing workspace starts a new trial draft. Existing conversations and the map are kept.</p><button className="secondary-button" onClick={()=>{update(newTrial(demo?'live':'demo'));setAi(null)}}>{demo?'Start from my conversations':'Start Noor’s fictional story'}</button></details></div>
 <ol className="trial-steps">{steps.map((s,i)=><li key={s} aria-current={trial.step===i?'step':undefined} className={trial.step===i?'current':trial.step>i?'done':''}><span>{trial.step>i?<Check size={15}/>:i+1}</span>{s}</li>)}</ol>
 {saveError&&<p role="alert" className="error-banner">{saveError}</p>}{errors.length>0&&<div role="alert" className="error-banner">{errors.map(e=><p key={e}>{e}</p>)}</div>}
 {trial.step===0&&<><div className="trial-section-heading"><div><span className="eyebrow">01 / THE EVIDENCE</span><h2>What are visitors actually asking for?</h2><p>Pick the messages that support your idea. A compliment or a question about hospitality is not a commitment to pay.</p></div><div className="trial-count"><strong>{parties}</strong><span>{demo?'parties':'visitor records'} selected<br/>0 confirmed bookings</span></div></div>
 <div className="trial-evidence">{notes.map(n=><label key={n.id} className={selected.includes(n.id)?'selected':''}><input type="checkbox" checked={selected.includes(n.id)} onChange={e=>update({selected:e.target.checked?[...selected,n.id]:selected.filter(id=>id!==n.id),approved:false,finished:false})}/><div><span className="eyebrow">{n.visitor}{(demo||n.demo)&&' · SAMPLE'}</span><blockquote>{n.text}</blockquote><small>{demo?'Scenario author’s topic labels':'Topics from local rules'}: {n.topics.join(' · ')||'No topic found'}</small></div></label>)}</div>{!notes.length&&<p>No saved visitor messages yet. <a href="#talk">Start a conversation</a> or choose Noor’s story above.</p>}
 {demo&&<details className="trial-ai"><summary><Cpu size={17}/> See where small AI helps</summary><p>Party 6 describes the activity without saying “roasting” or “tasting.” Try the optional English intent model on those exact words. Its job is to suggest the type of request; Noor still confirms its meaning and selects the evidence.</p><button className="secondary-button" onClick={analyze} disabled={busy||HOSTED_DEMO}>{busy?'Analyzing…':'Analyze Party 6 on this device'}</button><small>Explicit preparation: about 23 MB model + shared runtime (about 46 MB total if uncached). No transcript upload. Interest counts and cost calculations use ordinary code.</small>{ai&&<div className="trial-ai-result"><strong>{ai.accepted?ai.intent.replaceAll('_',' '):'Not sure — please clarify'}</strong><p>{ai.accepted?'Model suggestion; not a confirmed intention or booking.':'The model abstained. Ask the visitor what they would like to do.'}</p><small>{Math.round(ai.elapsedMs||0)} ms · English only · prototype trained on synthetic examples</small></div>}</details>}
 <div className="trial-actions"><button className="primary-button" onClick={()=>go(1)}>Plan from these messages <ArrowRight size={17}/></button></div></>}
 {trial.step===1&&<><div className="trial-section-heading"><div><span className="eyebrow">02 / NOOR SETS THE LIMITS</span><h2>Fit the experience around your work.</h2><p>{parties} reviewed {demo?'parties':'visitor records'} suggest interest. Confirm demand before buying supplies or reserving time.</p></div>{demo&&<button className="secondary-button" onClick={()=>{update({plan:{...DEMO_PLAN},approved:false,finished:false})}}>Use Noor’s example plan</button>}</div>
 <div className="trial-columns"><section className="white-card"><div className="trial-fields"><Field label="Experience name" value={plan.title} onChange={v=>changePlan('title',v)}/><Field label="Time to propose" value={plan.slot} onChange={v=>changePlan('slot',v)}/><Field label="Duration (minutes)" type="number" min="1" value={plan.duration} onChange={v=>changePlan('duration',v)}/><Field label="Maximum guests" type="number" min="1" value={plan.capacity} onChange={v=>changePlan('capacity',v)}/><Field label="Minimum confirmed guests" type="number" min="1" value={plan.minimum} onChange={v=>changePlan('minimum',v)}/><Field label="Price per guest (PKR)" type="number" min="0" value={plan.price} onChange={v=>changePlan('price',v)}/><Field label="Supplies per guest (PKR)" type="number" min="0" value={plan.variable} onChange={v=>changePlan('variable',v)}/><Field label="Other trial costs (PKR)" type="number" min="0" value={plan.fixed} onChange={v=>changePlan('fixed',v)}/></div><label className="trial-field">Public meeting instructions<textarea rows={3} value={plan.meeting} onChange={e=>changePlan('meeting',e.target.value)}/></label><a className="trial-map-link" href="#map"><MapPin size={17}/> Check Noor’s map & meeting point</a><p className="trial-fine">The existing map pin is illustrative. Agree the real location privately before a visit.</p><label className="trial-field">Access arrangements<textarea rows={2} value={plan.access} onChange={e=>changePlan('access',e.target.value)}/></label><label className="trial-field">Inclusions and boundaries<textarea rows={3} value={plan.boundary} onChange={e=>changePlan('boundary',e.target.value)}/></label></section>
 <aside className="trial-math"><span className="eyebrow">YOUR FIGURES, MADE VISIBLE</span><h2>A small test, with clear limits.</h2>{valid?<><dl><div><dt>At {plan.minimum} paying guests</dt><dd>PKR {money(calc.revenue)}</dd></div><div><dt>Entered trial costs</dt><dd>PKR {money(calc.cost)}</dd></div><div className="total"><dt>Amount left after these costs</dt><dd>PKR {money(calc.contribution)}</dd></div></dl><p>{calc.breakEven===null?'This price does not exceed the per-guest supplies cost. Revisit the plan.':`${calc.breakEven} paying guest${calc.breakEven===1?'':'s'} cover the entered costs.`}{calc.breakEven>Number(plan.capacity)&&' This exceeds your capacity; change the plan before offering it.'}</p></>:<p>Complete your plan to see the calculation.</p>}<small>This is arithmetic using your assumptions, not predicted demand or profit. Include your time, guide payment and other costs where relevant. Unentered costs are excluded.</small><div className="trial-owner"><ShieldCheck size={20}/><p>Noor chooses the activity, price, capacity and whether to proceed.</p></div></aside></div><div className="trial-actions"><button className="secondary-button" onClick={()=>go(0)}>Back to evidence</button><button className="primary-button" onClick={()=>go(2)}>Review the offer <ArrowRight size={17}/></button></div></>}
 {trial.step===2&&<><span className="eyebrow">03 / A CLEAR INVITATION</span><h2>Hospitality and a paid activity should be easy to distinguish.</h2><p>Read the details aloud or show them to the visitor. Noor must confirm availability separately.</p><div className="trial-columns"><article className="trial-offer"><span className="trial-badge">{demo?'DEMO OFFER · NOT BOOKABLE':'LOCAL OFFER DRAFT'}</span><pre>{offerText(plan,demo)}</pre><p lang="ur" dir="rtl">یہ ایک بامعاوضہ سرگرمی ہے۔ بکنگ سے پہلے قیمت، وقت اور ملاقات کی جگہ کی تصدیق کریں۔</p><small>“This is a paid activity. Confirm the price, time and meeting place before booking.” Authored Urdu template; fluent-speaker review needed before deployment.</small></article><aside className="white-card"><h3>Your final check</h3><p>Can you deliver this at the stated time and price? Has the visitor understood what is included?</p><label className="trial-check"><input type="checkbox" checked={trial.approved} onChange={e=>{update({approved:e.target.checked})}}/><span>{demo?'As Noor in this scenario, I have reviewed the price, workload and boundaries.':'I have reviewed the price, workload and boundaries.'}</span></label><button className="primary-button" disabled={!trial.approved} onClick={copy}><Copy size={16}/> Copy reviewed offer</button><p className="trial-fine">Copying does not contact anyone, publish a listing or create a booking.</p><a className="trial-map-link" href="#map"><MapPin size={17}/> Open meeting-point map</a></aside></div><div className="trial-actions"><button className="secondary-button" onClick={()=>go(1)}>Edit the plan</button><button className="primary-button" disabled={!trial.approved} onClick={()=>go(3)}>Record what happened <ArrowRight size={17}/></button></div></>}
 {trial.step===3&&<><span className="eyebrow">04 / CLOSE THE LOOP</span><h2>{trial.finished?'A decision backed by one small test.':'What happened when you tried it?'}</h2><p>{demo?'Scenario: three adults agree directly with Noor and attend. A fourth interested person does not book. Noor records the following illustrative outcome.':'Enter the result after the session, including cancellations or zero attendance. Safar does not collect payments or confirm bookings.'}</p>{trial.finished?<div className="trial-result"><span className="trial-badge">{demo?'SIMULATED RESULT':'OPERATOR-RECORDED RESULT'}</span><h2>{trial.outcome.decision==='repeat'?'Repeat the trial':trial.outcome.decision==='change'?'Change it before repeating':'Stop this experience'}</h2><div className="trial-result-stats"><div><strong>{trial.outcome.guests}</strong><span>guests attended</span></div><div><strong>PKR {money(Number(trial.outcome.revenue)-Number(trial.outcome.cost))}</strong><span>left after recorded costs</span></div></div><blockquote>{trial.outcome.feedback}</blockquote><h3>Noor’s next action</h3><p>{trial.outcome.next}</p><p className="trial-fine">One trial does not establish recurring demand or income. {demo?'No real visit, revenue or payment is represented here.':'Amounts are self-reported; unrecorded costs are excluded.'}</p><button className="secondary-button" onClick={()=>update({finished:false})}>Edit this review</button><button className="secondary-button" onClick={()=>go(0)}>Walk through this trial again</button></div>:<section className="white-card"><div className="trial-fields">{[['guests','Guests who attended'],['revenue','Total received (PKR)'],['cost','Total trial costs (PKR)']].map(([k,l])=><Field key={k} label={l} type="number" min="0" value={trial.outcome[k]} onChange={v=>update({outcome:{...trial.outcome,[k]:v}})}/>)}</div><label className="trial-field">What worked, and what should change?<textarea rows={3} value={trial.outcome.feedback} onChange={e=>update({outcome:{...trial.outcome,feedback:e.target.value}})}/></label><fieldset className="trial-decision"><legend>Your decision</legend>{[['repeat','Repeat'],['change','Change'],['stop','Stop']].map(([v,l])=><label key={v}><input type="radio" name="decision" value={v} checked={trial.outcome.decision===v} onChange={()=>update({outcome:{...trial.outcome,decision:v}})}/>{l}</label>)}</fieldset><label className="trial-field">Next action<textarea rows={2} value={trial.outcome.next} onChange={e=>update({outcome:{...trial.outcome,next:e.target.value}})}/></label><button className="primary-button" onClick={finish}>Save Noor’s decision <Check size={17}/></button></section>}<div className="trial-actions"><button className="secondary-button" onClick={()=>go(2)}>Back to the offer</button><a className="secondary-button" href="#home">Back home</a></div></>}
 {status&&<p role="status" className="notice">{status}</p>}<p className="trial-fine">Saved only in this browser. Model suggestions are optional; the full planning journey works without them. Delete the trial with “Delete all local data” in device settings.</p></div>
}
